#!/usr/bin/env zsh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.50
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# If no window on the current space is focused after a window is destroyed or
# minimized, or an application is hidden, focus the window under the cursor.
yabai -m signal --add event=window_destroyed \
  action="yabai -m window --focus mouse 2>/dev/null || true"
yabai -m signal --add event=window_minimized \
  action="yabai -m window --focus mouse 2>/dev/null || true"
yabai -m signal --add event=application_hidden \
  action="yabai -m window --focus mouse 2>/dev/null || true"

echo "yabai configuration loaded"
